# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 08:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_no', models.IntegerField(blank=True, default='1')),
                ('quantity', models.IntegerField(blank=True, default='1')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('item_no', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(blank=True, default='', max_length=1000)),
                ('item_category', models.CharField(blank=True, default='', max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Inventory'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
