# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='item_image',
            field=models.ImageField(default='', upload_to=shop.models.inventory_path),
        ),
    ]
